kind: ConfigMap
apiVersion: v1
metadata:
  generateName: k8s-executor
  labels:
    app: nextflow
data:
  k8s.config: |
    process.executor='k8s'
    k8s.namespace='intervene-dev'
    k8s.serviceAccount='nextflow-job'
    k8s.storageMountPath='/workspace'
  scm: |
    providers {
        ebi {
            server = 'https://gitlab.ebi.ac.uk'
            platform = 'gitlab'
        }
     }