kind: ConfigMap
apiVersion: v1
metadata:
  generateName: k8s-executor
  labels:
    app: nextflow
data:
  k8s.config: |
    process.executor='local'
    k8s.namespace='intervene-dev'
    k8s.serviceAccount='nextflow-job'
    k8s.storageClaimName='ssdnfsclaim'
    k8s.storageMountPath='/workspace'

