apiVersion: batch/v1
kind: Job
metadata:
  generateName: pgsc-calc-
  labels:
    app: nextflow
    # labels modified by Python during jobsubmitter ingestion
    submitter: consumer-0
    run-id: nxf-unique-run-id 
    version: dev 
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: nextflow-job
      containers:
        - args:
            # - nextflow run https://gitlab.ebi.ac.uk/gdp-public/pgsc_calc.git -r v1.3.0 --input /config/input.json -c /config/k8s.config
            - nextflow run  https://gitlab.ebi.ac.uk/gdp-public/pgsc_calc.git -r v1.3.0 --input /config/input.json -c /config/s3.config -c /config/k8s.config --outdir s3://intervene-test/test-calc --vzs
          command:
            - /bin/sh
            - '-c'
          env:
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['run-id']
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: NXF_PARAMS_FILE
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_params_file
            - name: NXF_OFFLINE
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_offline
            - name: NXF_ANSI_LOG
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_ansi_log
            - name: NXF_OPTS
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_opts
            - name: NXF_WORK
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_work
            - name: NXF_HOME
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_work
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: aws-access-key-id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: aws-secret-access-key
                  optional: false
            - name: NXF_SCM_FILE
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_scm_file
          image: 'docker.io/nextflow/nextflow:22.10.3'
          name: nextflow
          workingDir: /workspace
          resources:
            limits:
              cpu: 2
              memory: 4G
            requests:
              cpu: 2
              memory: 2G
          volumeMounts:
            - mountPath: /workspace
              name: vol-1
              readOnly: false
            - name: config
              mountPath: "/config"
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: vol-1
          persistentVolumeClaim:
            claimName: nfs-claim-new
        - name: config
          configMap:
            name: dummy-configmap # modified by python

