apiVersion: batch/v1
kind: Job
metadata:
  generateName: pgsc-calc-
  labels:
    app: nextflow
    # labels modified by Python during jobsubmitter ingestion
    submitter: consumer-0
    run-id: nxf-unique-run-id 
    version: dev 
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: nextflow-job
      containers:
        - args:
            - nextflow run hello -c /config/k8s.config
          command:
            - /bin/sh
            - '-c'
          env:
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['run-id']
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: NXF_PARAMS_FILE
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_params_file
            - name: NXF_OFFLINE
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_offline
            - name: NXF_ANSI_LOG
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_ansi_log
            - name: NXF_OPTS
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_opts
            - name: NXF_WORK
              valueFrom:
                configMapKeyRef:
                  name: nxf-base
                  key: nxf_work
          image: 'docker.io/nextflow/nextflow:21.10.6'
          name: nextflow
          resources:
            limits:
              cpu: 2
              memory: 4G
            requests:
              cpu: 2
              memory: 2G
          volumeMounts:
            - mountPath: /workspace
              name: vol-1
              readOnly: false
            - name: config
              mountPath: "/config"
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: vol-1
          persistentVolumeClaim:
            claimName: ssdnfsclaim
        - name: config
          configMap:
            name: dummy-configmap # modified by python 
