apiVersion: v1
kind: Pod
metadata:
  generateName: transfer-
  namespace: intervene-dev
  labels:
    app: transfer
spec:
  initContainers:
    - name: volume-mount-hack
      image: busybox
      command: [ "sh", "-c", "chown -R 1000:1000 /data" ]
      volumeMounts:
        - name: vol-1
          mountPath: /data
  containers:
  - name: init-transfer
    image: dockerhub.ebi.ac.uk/gdp-public/jobsubmitter/transfer:0.2.0
    imagePullPolicy: IfNotPresent
    command: ["transfer.sh"]
    env:
      - name: GLOBUS_SECRET_TOKEN
        valueFrom:
          secretKeyRef:
            name: globus
            key: secret_token
            optional: false
      - name: GLOBUS_BASE_URL
        valueFrom:
          configMapKeyRef:
            name: transfer-dummy-configmap  # edited by python
            key: GLOBUS_BASE_URL
            optional: false
      - name: GLOBUS_GUEST_COLLECTION_ID
        valueFrom:
          configMapKeyRef:
            name: transfer-dummy-configmap  # edited by python
            key: GLOBUS_GUEST_COLLECTION_ID
            optional: false
      - name: JOB_MESSAGE
        valueFrom:
          configMapKeyRef:
            name: transfer-dummy-configmap  # edited by python
            key: JOB_MESSAGE
            optional: false
  restartPolicy: Never
